### ISSUE TITLE
How to assign Authorization header?

### ISSUE THREAD

**Issue by valentinmarinro** [StefH/angular-odata-es5#11]
Hi @StefH , how to set up ODataConfiguration so I can add an Authorization header to below query?

```
const query: ODataQuery<recordedCalls> = this.odata.Query().Select(...);

PrimeNGDataTableODataQueryExtensions.applyLazyLoadEvent(query, event);

query.ExecWithCount()
        .subscribe((pagedResult: ODataPagedResult<recordedCalls>) => {
            this.calls = pagedResult.data;
            this.totalRecords = pagedResult.count;
        },
        (error) => {
            console.log('getPagedData ERROR ' + error);
        });
```

**Comment by StefH** [comment]
A possible solution would be to overwrite the `postRequestOptions` property with your own value.
https://github.com/StefH/angular-odata-es5/blob/master/src/angularODataConfiguration.ts#L24

Example:
```js
let postHeaders = new Headers({ 'Authorization': 'BASIC abc', 'Content-Type': 'application/json; charset=utf-8' });
let postRequestOptions: RequestOptions = new RequestOptions({ headers: postHeaders });
```

**Comment by valentinmarinro** [comment]
Hi @StefH , 

Thank you for your quick response, but it seems that ExecWithCount function is performing an http get with no config params, so the headers are not added to this get request.
https://github.com/StefH/angular-odata-es5/blob/master/src/angularODataQuery.ts#L54

Thanks,
Valentin

**Comment by StefH** [comment]
@valentinmarinro 
It should be fixed,  Exec() and ExecWithCount() to use **defaultRequestOptions** from config object.

**Comment by valentinmarinro** [comment]
Yep, it is working just fine now, thanks a lot!
