### ISSUE TITLE
Update to angular >=11

### ISSUE THREAD

**Issue by markyp8203** [StefH/angular-odata-es5#118]
Is it possible to update to angular >= 11?

**Comment by StefH** [comment]
I'm trying to fix it, however I need to fix first some other security issues, else I cannot publish to npm it seems...

**Comment by StefH** [comment]
@markyp8203 

New version `0.11.2` should be compatible with Angular 11.

Please test.

**Comment by markyp8203** [comment]
Thank you. It works (even with Angular 12 if I ignore peer dependencies warnings).

**Comment by StefH** [comment]
In that case, I'll also generate a `0.12` version which increases the dependencies .
