### ISSUE TITLE
Change Http -> HttpClient

### ISSUE THREAD

**Issue by Sir-J** [StefH/angular-odata-es5#21]
Are you planning to replace HTTP with HTTP Client?

**Comment by StefH** [comment]
Yes I'm planning this, however I've not yet a timeline for this.

**Comment by Sir-J** [comment]
I create PR

**Comment by StefH** [comment]
Opened because of bugs in PR.

**Comment by StefH** [comment]
Please review my changes at : https://github.com/StefH/angular-odata-es5/commit/3f803c52a7d0bb48a4553fa06486203d10a757e2

**Comment by Sir-J** [comment]
I watched. I do not have any questions.

**Comment by StefH** [comment]
Ok. Thanks for submitting and reviewing the code. I'll make a new nom based on this within few days.

**Comment by StefH** [comment]
Published new version to https://www.npmjs.com/package/angular-odata-es5
