### ISSUE TITLE
Saving query parameters

### ISSUE THREAD

**Issue by Sir-J** [StefH/angular-odata-es5#23]
If I doing Odata request with parameters and then doing Delete request, all parameters from first request sended in second request.
For example:
```javascript
this.odata = odataFactory.CreateService<T>(serviceName); 
// sending $top=100
this.odata.Query().Top(100).Exec();
// and here sending $top=100
this.odata.Delete(1);
```

Tell me, is this how it should be? I understand that Delete should be sent without parameters (except for the key parameter)

**Comment by StefH** [comment]
Sounds like a bug, I will check.

**Comment by StefH** [comment]
Fixed; see new version on npm

**Comment by Sir-J** [comment]
Thanks!
