### ISSUE TITLE
Consider assuming function params are serialized if they are a string

### ISSUE THREAD

**Issue by markwaddle** [StefH/angular-odata-es5#29]
When calling a custom function, it would be nice if it allowed custom parameter serialization. It makes sense that this could happen when the params were sent as a string, in which case they would just be inserted within the parens and sent off as is ...

**Comment by StefH** [comment]
Still an issue ?

**Comment by markwaddle** [comment]
The recent fixes negate the need for this. Thanks

**Comment by StefH** [comment]
Nice !
