### ISSUE TITLE
Observable.throw is not a function

### ISSUE THREAD

**Issue by Farenheith** [StefH/angular-odata-es5#39]
Hello, I'm getting the error described in the title when I'm using Exec and the url retrive a status 400 error.

A workaround to this issue was changing this line in angularODataQuery.js:

`import { Observable } from 'rxjs/Observable';`

To this

`import { Observable } from 'rxjs/Rx';`

So the whole Rx Package is imported and also the static method Observation.throw come together, but it's not the best approach.

This issue explain in details the problem and the best solution:
https://github.com/ReactiveX/rxjs/issues/1866

**Comment by StefH** [comment]
Is this the only place, or should I replace all ?

**Comment by Farenheith** [comment]
At first, only in the sourcecodes where you use Observable.throw.

But have in mind this is not the best solution as you will include the whole Rx package on your library just because of one static method, increasing considerably the bundle size.

I tried to import only 'rxjs/add/observable/throw' as it's stated in https://github.com/ReactiveX/rxjs/issues/1866, but I couldn't make it work.
As I needed a quick workaround for that matter I stick with importing the whole package, but I'll take a look on it again at some moment.

**Comment by salcio** [comment]
I've only added
`import 'rxjs/add/observable/throw'` and it worked. At least in AngularODataQuery.js. 

According to multiple forum posts ([for example](https://stackoverflow.com/questions/45553341/should-i-use-both-import-rxjs-rx-and-import-observable-from-rxjs-obse)) I've seen importing from 
`import { Observable } from 'rxjs/Rx';`

is not a good idea. That will import whole package and it will dramatically increase the size of the output.

**Comment by StefH** [comment]
Fixed.

NPM 0.2.9 is created.
