### ISSUE TITLE
Aggregation-related odata queries 

### ISSUE THREAD

**Issue by sebaiona** [StefH/angular-odata-es5#42]
Hi @StefH ,

I'd want to know if there is a possibility to use your package to `select distinct` values or to do `sum` operation for example, like in 7.1 and 7.2 in the following link.

http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs02/odata-data-aggregation-ext-v4.0-cs02.html#_Toc435016609 

I didn't find any solution and it kind of bothers me for what I'd need to do...

Please tell me if I'm wrong...

Thanks in advance !

**Comment by StefH** [comment]
Good question. This is not supported out of the box. I've to think on this...

**Comment by StefH** [comment]
Maybe you can use the new functionality:

https://github.com/StefH/angular-odata-es5/pull/45
