### ISSUE TITLE
Programmatically change arrays of OrderBy or Filter of ODataQuery

### ISSUE THREAD

**Issue by sebaiona** [StefH/angular-odata-es5#43]
Hi @StefH,

Sorry to bother you again but do you think there could be a way to change programmatically the `OrderBy` or `Filter`.

I explain myself : 

I use **angular-odata-es5** and **PrimeNG-DataTable-Extensions** and after executing `applyLazyLoadEvent` I would like to modify the sorting depending on different cases.

If I do `query.OrderBy` or `query.Filter` it replaces the existing ones and there is no way to get what were the already existing values.

The problem is that these values are in private and there is no way to get them  : 
- `private _filter: string[] = [];`
- `private _orderBy: string[] = [];`

If there would be two functions returning these two arrays (a sort of `GetOrderBy` and `GetFilter`), then I could do anything I want on the arrays and do again `OrderBy` or `Filter`.

Thanks in advance !

**Comment by StefH** [comment]
I think you can use a trick to access private fields...

Try this:
``` ts
  const o: string[] = this.query['_orderBy'];
  console.log('_orderBy : ' + o.join('---'));

  this.query
    .ExecWithCount()
```

**Comment by sebaiona** [comment]
I don't know why I didn't think about this trick...

I can do anything I need with your solution, so thanks a lot !

**Comment by StefH** [comment]
Cool.
