### ISSUE TITLE
Consider supporting $count endpoint on resource path

### ISSUE THREAD

**Issue by salcio** [StefH/angular-odata-es5#46]
As in title. Could you add support for $count endpoint. Example: 

http://host/service/Categories/$count
http://host/service/Products/$count?$filter=Category eq 'Test'

**Comment by StefH** [comment]
Would `UseCount()` be a good name?

So like:
``` js
query
  .UseCount()
  .Filter(`x gt 1`)
```

**Comment by salcio** [comment]
But then we would still need to call exec, wouldn’t we ? 

Should the count be some sort of exec method as it will have to return observable<int>

What about just Count() or ExecCount(). 

Regards
Łukasz Salamon

**Comment by StefH** [comment]
Ah. Correct, it should always return a `Observable<number>`.

`Count()` is a good name maybe
`ExecCount()` could be confusing with `ExecWithCount()`

Or maybe rename all methods:
`Exec()` --> `Exec`
`ExecWithCount()` --> `ExecAsPagedResult()`
`**Count**` --> `ExecAsCount()`

?

**Comment by salcio** [comment]
Agreed that it might be confusing with ExecWithCount() without the rename of all. 
I like the Exec and ExecAsCount. I’m not sure about ExecAsPagedResult. Maybe ExecWithCount isn’t that bad after the rename: 

Exec -> Observable<[entity]>
ExecAsCount -> Observable<number>
ExecWithCount -> Observable<[PagedResul]t>

**Comment by salcio** [comment]
One thing to mention is that with the rename that will be a breaking change. So next major version I guess.

**Comment by StefH** [comment]
What about keeping only `Exec()` ? So just returning multiple possible results?

**Comment by salcio** [comment]
And how would say which one we want ? 
Separate methods to be called before exec ? 

Regards
Łukasz Salamon

**Comment by StefH** [comment]
Normal:
``` js
const result = query
  .Filter(`x gt 1`)
  .Exec();
```

Count
``` js
const result = query
  .Filter(`x gt 1`)
  .AsCount()
  .Exec();
```

Paging
``` js
const result = query
  .Filter(`x gt 1`)
  .AsPagedResult()
  .Exec();
```

**Comment by salcio** [comment]
Yes I think that looks ok. 

Regards
Łukasz Salamon

**Comment by StefH** [comment]
I found a better solution : [www.typescriptlang.org/play](https://www.typescriptlang.org/play/#src=type%20User%20%3D%20string%3B%0Atype%20Observable%3CT%3E%20%3D%20T%3B%20%0A%0Aclass%20X%20%7B%0A%20%20_url_User%3A%20string%3B%0A%20%20_http%3A%20any%3B%20%0A%20%20getUsers()%3A%20Observable%3CUser%3E%3B%0A%20%20getUsers(followers%3A%20false)%3A%20Observable%3CUser%3E%3B%0A%20%20getUsers(followers%3A%20true)%3A%20Observable%3CUser%5B%5D%3E%3B%0A%20%20getUsers(followers%3F%3A%20boolean)%3A%20Observable%3CUser%20%7C%20User%5B%5D%3E%20%7B%0A%20%20%20%20this._url_User%20%2B%3D%20followers%20%3F%20%22%2Ffollowers%22%20%3A%20%22%22%3B%0A%20%20%20%20return%20this._http.get(this._url_User).map(res%20%3D%3E%20res.json())%3B%0A%20%20%7D%0A%7D%0A%0Avar%20x%20%3D%20new%20X()%3B%0Avar%20oneUser%3A%20User%3B%0Avar%20manyUsers%3A%20User%5B%5D%3B%0A%0A%2F%2F%20All%20valid%3A%0AoneUser%20%3D%20x.getUsers()%3B%0AoneUser%20%3D%20x.getUsers(false)%3B%0AmanyUsers%20%3D%20x.getUsers(true)%3B)

Which looks in this project like:
``` js
public Exec(): Observable<T[]>;
public Exec(returnType: ODataExecReturnType.Count): Observable<number>;
public Exec(returnType: ODataExecReturnType.PagedResult): Observable<ODataPagedResult<T>>;
public Exec(returnType?: ODataExecReturnType): Observable<T[] | ODataPagedResult<T> | number> {
  // code here ...
}
```

**Comment by salcio** [comment]
Sounds good. 

Regards
Łukasz Salamon

**Comment by StefH** [comment]
NPM updated

**Comment by StefH** [comment]
Can you test ?

**Comment by salcio** [comment]
Yes I will today. 

Regards
Łukasz Salamon

**Comment by salcio** [comment]
Seems to work well :) thank you.

**Comment by StefH** [comment]
Thanks
