### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_1_rxjs_Observable__.Observable.throw is not a function when server returnes 500

### ISSUE THREAD

**Issue by salcio** [StefH/angular-odata-es5#47]
When server returns a 500 status and exception is thrown with message: 

`__WEBPACK_IMPORTED_MODULE_1_rxjs_Observable__.Observable.throw is not a function`

It is thrown in a angularODataQuery.js file at line 59 
`return Observable.throw(err);`

Quick google shows that it could because of missing import for throw method: 

`import 'rxjs/add/observable/throw'`

**Comment by salcio** [comment]
Sorry haven't seen that it was already raised in issue #39. Please close as a duplicate.

**Comment by StefH** [comment]
I will take a look at the code and make a fix.
