### ISSUE TITLE
toCommaString break Datetime comparator

### ISSUE THREAD

**Issue by bastienlemaitre** [StefH/angular-odata-es5#48]
Hi
The toCommaString present into this file : 'angular-odata-es5/src/angularODataOperation.ts' seems  to broke the Datetime comparator.
For example:
`SignatoryID eq ${this.signatory.ID} and EndDate lt ${new Date().toISOString()}`
Format -> `SignatoryID eq 14 and EndDate ge 2018-02-07T09:58:30.897Z`
toCommaString  ->  `SignatoryID eq 14 and EndDate ge 2018-02-07T09:58:30/897Z`
The dot is replaced by a slash..

**Comment by bastienlemaitre** [comment]
Maybe add a regex to handle ISODatetime ?

**Comment by StefH** [comment]
OK. This has to be fixed.

**Comment by bastienlemaitre** [comment]
Does we really need toCommaString ?

**Comment by StefH** [comment]
No, I have to rewrite the code. I keep you updated on progress...

**Comment by bastienlemaitre** [comment]
Thanks !

**Comment by StefH** [comment]
Fixed.
See new NPM : 0.2.10
