### ISSUE TITLE
Issue: CustomCollectionAction and CustomAction to use this.config.postRequestOptions

### ISSUE THREAD

**Issue by salcio** [StefH/angular-odata-es5#49]
At the moment CustomCollectionAction and CustomAction methods when making requests (posts) are using 'this.config.defaultRequestOptions'. 

Shouldn't they use this.config.postRequestOptions ?

**Comment by diegomvh** [comment]
Hi, i'm currently use angular-odata-es5 in a project and had the same issue in action's invocations.

When change the source for use `postRequestOptions` the header **'Content-Type': 'application/json; charset=utf-8'** is appended to the request and te problem (server error) of calling the actions disappears.

**Comment by StefH** [comment]
New NPM is created.
