### ISSUE TITLE
Feature: add CompositeKeys support

### ISSUE THREAD

**Issue by bastienlemaitre** [StefH/angular-odata-es5#50]
How can i patch composed IDS ?

Thanks

**Comment by StefH** [comment]
Can you explain this with an example ?

**Comment by bastienlemaitre** [comment]
Your current package support's only one primary key:
- odata/Person(1)
But if I have composed IDS, I can't do:
- odata/Person(ID1=1,ID2=21)

**Comment by StefH** [comment]
OK I see.

https://github.com/OData/ODataSamples/tree/master/WebApi/v4/ODataCompositeKeySample

**Comment by StefH** [comment]
Please try NPM version 0.3.1

**Comment by StefH** [comment]
New version added to npm.

**Comment by StefH** [comment]
Closing...

**Comment by bastienlemaitre** [comment]
Thanks !
