### ISSUE TITLE
Question : Complete example with service-url

### ISSUE THREAD

**Issue by src-mgra** [StefH/angular-odata-es5#51]
Hi,

I want to access a odata-service with angular 2 bzw. ionic. It seems this component can make
this a little bit more comfortable.
Do you have a complete example with a
service.svc/$metadata
by using the component ?
Or is it necessary to implement the $select - urls manually ?

kind regards
  michael

**Comment by StefH** [comment]
I'm not sure if this helps you?
https://github.com/StefH/angular-odata-es5/blob/master/demo/employeeGridOData.component.ts

**Comment by src-mgra** [comment]
Out dated
