### ISSUE TITLE
OrderBy on nested properties broken

### ISSUE THREAD

**Issue by sebaiona** [StefH/angular-odata-es5#53]
Hi @StefH !

I don't know when but I think there is an update where you modified your code and it seems that the OrderBy on nested properties doesn't work anymore...
(Perhaps other operations with nested properties are also broken, I didn't try...)

It creates an url which looks like something like `...$orderby=Boss.Name` instead of `...$orderby=Boss/Name` which is the good syntax...

Thanks in advance !

PS : By the way, would it be possible to update `PrimeNG-DataTable-Extensions` to be compatible with the most recent version of `angular-odata-es5` ?

**Comment by StefH** [comment]
1] I had to revert my code because it did not work in all scenarios. So for now, always use the `/`.

Example:
``` js
query
            .Filter(`x gt 1 and Boss/Filter eq 42 and EndDate lt 2018-02-07T09:58:30.897Z`)
            .Apply(['groupby((Age))'])
            .Expand('EXP')
            .Top(10)
            .Skip(20)
            .Select(['s1', 's2', 'Boss/Select'])
            .OrderBy(['y', 'Boss/OrderBy']);
```

2] I've uploaded new version from PrimeNG-DataTable-Extensions to npm.

**Comment by sebaiona** [comment]
Thanks for PrimeNG-DataTable-Extensions !

For now, that's kind of what I do to keep it working.
But given though I use `PrimeNG-DataTable-Extensions`, I replace `.` by `/` after the `applyLazyLoadEvent`.

No big deal.

**Comment by StefH** [comment]
Closing...
