### ISSUE TITLE
Setting Post Headers

### ISSUE THREAD

**Issue by GalenSmallen** [StefH/angular-odata-es5#54]
Trying to set post headers.

``` ts
config.baseUrl = this.DataServiceURL;
config.postRequestOptions.headers = new HttpHeaders({
  'Accept': 'application/json',
  'Content-Type': 'application/json; charset=utf-8',
  'Session': ''});
```
Never seems to set the headers.

Am i missing something?

**Comment by StefH** [comment]
1]
I've added a unit test here:
https://github.com/StefH/angular-odata-es5/blob/master/test/angularODataService.spec.ts#L130
(However I cannot test the headers, see also https://stackoverflow.com/questions/50630377/how-to-use-a-custom-matcher-when-using-tohavebeencalledwith-in-jasmine-test

2]
For the real working code; I've added a post call to the odata api see here: https://github.com/StefH/angular-odata-es5/blob/master/demo/employeeGridOData.component.ts#L46

**Comment by SergeiNarozhnyi** [comment]
@StefH Headers are not passed through config.postRequestOptions.headers, so POST is sent without needed headers.

**Comment by StefH** [comment]
I noticed yesterday, sorry. I'm working on it.

**Comment by StefH** [comment]
@SergeiNarozhnyi 0.7.4 should fix it.
