### ISSUE TITLE
Question: POST Example

### ISSUE THREAD

**Issue by sachinpsingh** [StefH/angular-odata-es5#55]
There is no POST example given in documentation, Can you please provide one post sample through this component from angular

**Comment by StefH** [comment]
A POST example looks like this:

``` ts
const service = factory.CreateService<IEmployee>('Employees');
const employee: IEmployee = {
	EmployeeID: 1,
	FirstName: 'f',
	LastName: 'l',
	City: 'c',
	BirthDate: null,
	Orders: null,
	Boss: null
};

const result = service.Post(employee);
```
I'll add this as a unit-test...

Does this help you?

**Comment by sachinpsingh** [comment]
Thanks, for the code, I tried this same   POST method is not firing up, do i needs to do any other configuration for headers?

**Comment by StefH** [comment]
Your issue is maybe related to https://github.com/StefH/angular-odata-es5/issues/54, I'll need to investigate and maybe add some more tests and real POST code in my example project.

**Comment by StefH** [comment]
1]
I've added a unit test here:
https://github.com/StefH/angular-odata-es5/blob/master/test/angularODataService.spec.ts#L130
(However I cannot test the headers, see also https://stackoverflow.com/questions/50630377/how-to-use-a-custom-matcher-when-using-tohavebeencalledwith-in-jasmine-test

2]
For the real working code; I've added a post call to the odata api see here: https://github.com/StefH/angular-odata-es5/blob/master/demo/employeeGridOData.component.ts#L46
