### ISSUE TITLE
Issue: Upgrade to Angular 6

### ISSUE THREAD

**Issue by jonest** [StefH/angular-odata-es5#56]
I'm attempting to upgrade to Angular 6 and this is the only package I have that hasn't upgraded. I'm using `rxjs-compat` currently, but wouldn't mind removing it if I can get this upgraded :)

**Comment by gagle** [comment]
+1. Please update to rxjs 6.

**Comment by salcio** [comment]
Any chance we can have the rxjs 6 update ?

**Comment by StefH** [comment]
Thanks for the reminder. There is a PR ready for this, but I need to make time this weekend to review and merge.

**Comment by StefH** [comment]
0.4.0 is added to npm
