### ISSUE TITLE
Getting rxjs__WEBPACK_IMPORTED_MODULE_0__.Observable.throw is not a function

### ISSUE THREAD

**Issue by salcio** [StefH/angular-odata-es5#59]
Hi, 

I'm using version 0.4.0.

I'm getting rxjs__WEBPACK_IMPORTED_MODULE_0__.Observable.throw is not a function error whenever server returns error status. I guess it's because with rxjs version 6.0.0 we should use
`import {throwError} from 'rxjs'` and then `throwError(e)` rather then Observable.throw(e).

**Comment by jonest** [comment]
@salcio My bad! I must have missed that :) I removed the shim package `rxjs-compat` that likely masked that error so it _should_ be good after that pull request merges.

**Comment by salcio** [comment]
And when can we expect pull request merge ?

**Comment by StefH** [comment]
PR is merged, however the demo is broken. Fixing that now...

**Comment by StefH** [comment]
npm 0.5.0 is uploaded
