### ISSUE TITLE
Allow option to $expand on PUT/POST/PATCH

### ISSUE THREAD

**Issue by jonest** [StefH/angular-odata-es5#61]
OData allows the ability to do something like a `POST` with an `$expand` which then returns an object with an expanded property, e.g.:
## Request
```http
POST http://localhost/SomeService/v1/SomeResource?$expand=NestedObjects
Accept: application/json
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

{
  "Name": "Dummy Object",
  "NestedObjects": [
    {
      "Name": "Dummy Nested Object"
    }
  ]
}
```
## Response
```http
HTTP/1.1 200 OK
Content-Type: application/json; odata.metadata=minimal
Location: http://localhost/SomeService/v1/SomeResource?$expand=NestedObjects
OData-Version: 4.0

{
  "@odata.context": "http://localhost/SomeService/v1/$metadata#SomeResource/$entity",
  "Id": 1234,
  "Name": "Dummy Object",
  "NestedObjects": [
    {
      "Id": 4321,
      "Name": "Dummy Nested Object"
    }
  ]
}
```

In a specific use case that I'm using, we `PUT` an object with a nested object to update both the parent and the children in the database. When we get a response, it'll just return the top level object by default unless we include the `$expand` operator

**Comment by jonest** [comment]
I'm happy to work on adding this, but I'd like to hear some thoughts/get some guidance on how best to tackle this :)

**Comment by jonest** [comment]
I started taking a peek through the code to configure this similar to the `Get( ... )` operation that currently exists and saw that there are `PostOperation<T>`, `PutOperation<T>`, and `PatchOperation<T>` that have been commented out with a comment `//ToDo: Check ODataV4`. I'm not entirely sure what problem exists where this was left like this.

Would you mind elaborating at all on this @StefH ?

Thanks!

**Comment by StefH** [comment]
Actually I don't know the full details on this code part. I think I copied this from the older project.
And I never got the chance to analyze and implement this functions.

If you have time, you can add this (if possible including unit-tests)
