### ISSUE TITLE
upgrade to rxjs 6.3

### ISSUE THREAD

**Issue by cmeyertons** [StefH/angular-odata-es5#68]
needed for upgrading angular to latest

**Comment by StefH** [comment]
Should I also upgrade Angular to a later version?

**Comment by cmeyertons** [comment]
yeah that would be optimal -- upgrade everything to latest

**Comment by markwaddle** [comment]
angular@7.0.4, which will pull in rxjs@6.3.3

**Comment by markwaddle** [comment]
see pr #72

**Comment by sebaiona** [comment]
Indeed it would be great !

Until it's done, I put the `rxjs 6.3` manually in the `node_modules` folder of `angular-odata-es5` to make it work.
It allows me to compile and make it work, but it's not ideal...

What @markwaddle did should do the job!

**Comment by StefH** [comment]
https://github.com/StefH/angular-odata-es5/pull/72

**Comment by StefH** [comment]
npm version `0.7.1`
