### ISSUE TITLE
feature request: expose URL to be used by other sources

### ISSUE THREAD

**Issue by cmeyertons** [StefH/angular-odata-es5#69]
Hi there,

Great library!

It would be handy if the URL that is used could be accessed anywhere in the pipeline.

i.e. instead of `Exec()` a user could invoke `Url()` or `Uri()` and get the built URL up to that point.  This would allow this great library to be used when there are maybe other kinds of odata sources (i.e. DevExtreme's grid data source)

**Comment by jonest** [comment]
Great idea! I'm not exactly sure what you mean by other OData sources though. Do you have some pseudo code to illustrate what you mean?

**Comment by cmeyertons** [comment]
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ODataService/Angular/Light/

```
this.dataSource = {
            store: {
                type: 'odata',
                url: 'https://js.devexpress.com/Demos/DevAV/odata/Products'
            },
            select: [
                'Product_ID',
                'Product_Name',
                'Product_Cost',
                'Product_Sale_Price',
                'Product_Retail_Price',
                'Product_Current_Inventory'
            ],
            filter: ['Product_Current_Inventory', '>', 0]
        }
```

this example is how you can provide a URL to DevExtreme.  I'd like to be able to use this lib to give the URL to DevExtreme because creating it by hand feels "dirty" and is more error prone

**Comment by StefH** [comment]
What would be a good name ?
`getUrl()` seems ok ?

**Comment by StefH** [comment]
NPM is updated
