### ISSUE TITLE
add ability to supply custom query parameters

### ISSUE THREAD

**Issue by cmeyertons** [StefH/angular-odata-es5#70]
we have a use case where we want to supply custom query parameters.

route looks like:

http://localhost:61868/route/v1/Reports?effectiveDate=2018-06-30

it would be great if we could supply Param like so.

```
service.Query().Param('effectiveDate', '2018-06-30').Exec()
```

also, thanks for getting the GetUrl functionality out so quick!

**Comment by StefH** [comment]
Thank you, I'll merge your PR to master.
