### ISSUE TITLE
Custom collection function is not parsed with handleResponse

### ISSUE THREAD

**Issue by flobiber** [StefH/angular-odata-es5#78]
I try it like that:

``` ts
this.serviceFactory.User.CustomCollectionFunction('Me')
      .pipe(
        first()
      ).subscribe( (me) => {
        this.me = me;
        console.log(me);
      });
```

But the result isn't the data i want. It is the whole odata content, that isn't handled by the handleResponse method.

**Comment by StefH** [comment]
OK, I'll take a look at the code, or you want to make a PR, that's also fine.

**Comment by StefH** [comment]
There is no way the code could know what is returned by the the custom function `Me`, so you need to parse the OData response by yourself.

**Comment by flobiber** [comment]
Currently i have to do it like that: 

```
this.serviceFactory.User.CustomCollectionFunction('Me')
      .pipe(
        first(),
        map((data) => data.body.value) <-------##### Look at this line
      ).subscribe( (me) => {
        this.me = me;
        console.log(me);
      });
```

I think the marked line should be done by the library... ;)
