### ISSUE TITLE
CustomFunction formats odata call incorrectly

### ISSUE THREAD

**Issue by ernie-suplari** [StefH/angular-odata-es5#8]
Expect:
/odata/entity/functionName()

Actual:
/odata/entity('key')/functionName

Looking at the source:

```
 public CustomFunction(key: string, actionName: string): Observable<any> {
        return this._http.get(this.getEntityUri(key) + '/' + actionName, this.config.defaultRequestOptions).map(resp => resp.json());
    }
```

Passing it a key seems unneeded, functions are called on the entities so just a functionName is required. 

Also looks like a copy paste bug that the second parameter should be functionName instead of actionName. 

It would also be nice if it took an args array of key/value pair, but I can do a PR for that.

**Comment by StefH** [comment]
Thanks for finding this.

You can make a PR to fix it. And if possible a second PR for the args. Also if possible investigate if you can make unit tests.

**Comment by ernie-suplari** [comment]
I submitted a PR to address the no parameter version of the custom function. I also added a unit test for it.

**Comment by ernie-suplari** [comment]
Can we release these changes to the NPM package?

**Comment by StefH** [comment]
Done
