### ISSUE TITLE
Angular 9 update

### ISSUE THREAD

**Issue by jornare** [StefH/angular-odata-es5#88]
It seems the library already works fine with Angular 9, but the installation throws a warning because peer dependencies lists @angular/core <9

**Comment by sainisagar310** [comment]
+1

The same happens with the Angular version 10.  Could anyone help with it?

**Comment by StefH** [comment]
Should I fix this and create a new library version like `9.x.x` for angular 9?

Should I fix this and create a new library version like `10.x.x` for angular 10?

**Comment by elliotleelewis** [comment]
> Should I fix this and create a new library version like `9.x.x` for angular 9?
> 
> Should I fix this and create a new library version like `10.x.x` for angular 10?

@StefH Neither, you can use a version range that matches both of those versions. :)

**Comment by StefH** [comment]
How?

**Comment by elliotleelewis** [comment]
`version: ">=8.0.0 <11.0.0"`

See here: https://docs.npmjs.com/misc/semver#ranges
