### ISSUE TITLE
Cannot build project with Angular v10

### ISSUE THREAD

**Issue by matracey** [StefH/angular-odata-es5#99]
#### Dependencies
`"@angular/animations": "^10.0.3",`
`"@angular/common": "^10.0.3",`
`"@angular/compiler": "^10.0.3",`
`"@angular/core": "^10.0.3",`
`"@angular/forms": "^10.0.3",`
`"@angular/localize": "^10.0.3",`
`"@angular/platform-browser": "^10.0.3",`
`"@angular/platform-browser-dynamic": "^10.0.3",`
`"@angular/router": "^10.0.3",`
`"angular-odata-es5": "^0.8.4",`
#### Dev Dependencies
`"@angular-devkit/build-angular": "^0.1000.2",`
`"@angular/cli": "^10.0.2",`
`"@angular/compiler-cli": "^10.0.3",`
`"@angular/language-service": "^10.0.3",`

### Description
Running the `ng build` command outputs an error.

```
node_modules/angular-odata-es5/angularOData.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

3     static forRoot(): ModuleWithProviders;
                        ~~~~~~~~~~~~~~~~~~~
```

**Comment by StefH** [comment]
I will investigate this.

And I think it's best that the library should support version 10. But maybe supporting 9 (https://github.com/StefH/angular-odata-es5/issues/88) will also solve this project.

**Comment by matracey** [comment]
> I will investigate this.
> 
> And I think it's best that the library should support version 10. But maybe supporting 9 (#88) will also solve this project.

Per the details [here](https://angular.io/guide/migration-module-with-providers), `ModuleWithProviders<T>` has been optional since Angular 7. It looks like it's required in Angular 10 now, though.

**Comment by pbruvoll** [comment]
Any progress on this issue?

**Comment by mhollier** [comment]
Also interested in a fix for this issue found during Angular 10 migration.

**Comment by matracey** [comment]
I have raised #107 with a fix for this issue. @StefH, please help to review this PR. :)

**Comment by StefH** [comment]
@matracey Thanks a lot. I will try to make a new release. Keep a watch on this issue or npm.
